name: bowyer_cli
description: CLI shell for Bowyer admin panel.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  bowyer_core:
    path: ../core
  args: ^2.6.0
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
