// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Ninth House Studios LLC

import 'package:arrow_options/arrow_options.dart';

const _starSweNames = <Star, String>{
  Star.sheratan: ',betAri',
  Star.fortyOneArietis: ',41Ari',
  Star.alcyone: 'Alcyone',
  Star.aldebaran: 'Aldebaran',
  Star.meissa: ',lamOri',
  Star.betelgeuse: 'Betelgeuse',
  Star.pollux: 'Pollux',
  Star.asellus: ',delCnc',
  Star.epsilonHydrae: ',epsHya',
  Star.regulus: 'Regulus',
  Star.zosma: ',delLeo',
  Star.denebola: 'Denebola',
  Star.algorab: ',delCrv',
  Star.spica: 'Spica',
  Star.arcturus: 'Arcturus',
  Star.zubenelgenubi: ',alf02Lib',
  Star.dschubba: ',delSco',
  Star.antares: 'Antares',
  Star.shaula: ',lamSco',
  Star.kausMedia: ',delSgr',
  Star.nunki: ',sigSgr',
  Star.altair: 'Altair',
  Star.rotanev: ',betDel',
  Star.lambdaAquarii: ',lamAqr',
  Star.markab: 'Markab',
  Star.algenib: 'Algenib',
  Star.zetaPiscium: ',zetPsc',
  Star.sirius: 'Sirius',
  Star.canopus: 'Canopus',
  Star.rigel: 'Rigel',
  Star.procyon: 'Procyon',
  Star.achernar: 'Achernar',
  Star.capella: 'Capella',
  Star.vega: 'Vega',
  Star.rigilKentaurus: ',alfCen',
  Star.castor: 'Castor',
  Star.fomalhaut: 'Fomalhaut',
  Star.deneb: 'Deneb',
  Star.mimosa: ',betCru',
  Star.acrux: ',alfCru',
  Star.hamal: 'Hamal',
  Star.polaris: 'Polaris',
  Star.bellatrix: 'Bellatrix',
  Star.elNath: 'El Nath',
  Star.alnilam: 'Alnilam',
  Star.alnitak: ',zetOri',
  Star.mintaka: ',delOri',
  Star.alhena: ',gamGem',
  Star.alphard: 'Alphard',
  Star.rasalhague: 'Rasalhague',
  Star.sabik: ',etaOph',
  Star.zubeneschamali: ',betLib',
  Star.mesarthim: ',gamAri',
  Star.botein: ',delAri',
  Star.omicronTauri: ',omiTau',
  Star.zetaTauri: ',zetTau',
  Star.oneGeminorum: ',1Gem',
  Star.kappaGeminorum: ',kapGem',
  Star.chiCancri: ',chiCnc',
  Star.acubens: ',alfCnc',
  Star.kappaLeonis: ',kapLeo',
  Star.nuVirginis: ',nu.Vir',
  Star.muVirginis: ',mu.Vir',
  Star.fortyEightLibrae: ',48Lib',
  Star.tauScorpii: ',tauSco',
  Star.fortyFiveOphiuchi: ',45Oph',
  Star.nash: ',gam02Sgr',
  Star.omegaSagittarii: ',omeSgr',
  Star.dabih: ',betCap',
  Star.denebAlgedi: ',delCap',
  Star.iotaAquarii: ',iotAqr',
  Star.phiAquarii: ',phiAqr',
  Star.gammaPiscium: ',gamPsc',
  Star.alrescha: ',alfPsc',
  Star.galacticCenter: ',SgrA*',
};

String sweNameFor(Star star) => _starSweNames[star]!;
