name: arrow_tool
description: Test fixture generation for Arrow.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  arrow_options:
    path: ../options
  arrow_swe:
    path: ../swe
